application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
  - url: /static/client.js
    static_files: static/client.js
    upload: static/client.js

  - url: /static/site.css
    static_files: static/site.css
    upload: static/site.css

  - url: /.*
    script: _go_app
